### PR TITLE
feat: Add interactive prompt

### PR DESCRIPTION
**Pull request by CRKatri**
This PR adds an interactive prompt that I mentioned wanting in a comment on #4. I also fixed some other issues that I had run into, included extraneous newlines in the ls output, and letting cat accept multiple files.

https://user-images.githubusercontent.com/48231187/159779121-c668e4e2-4e5a-4ee6-be65-a713f1ac1a22.mp4

### CODE REVIEW

**Comment by blacktop** [comment]
[HOLY SHIZ](https://www.youtube.com/watch?v=rwR9JArHWaM)

**Comment by blacktop** [comment]
Is it possible to add tab complete to ls?  I guess you would know about the folders/files in the cwd, but to tab tab you'd need to run a "ls" in the background?

**Comment by CRKatri** [comment]
Good idea. I'm trying to think of how to implement this permanently though. Because just saving the current cwd would help when going deeper into the tree.

**Comment by blacktop** [comment]
Where you going to try and implement tab tab in this PR?

**Comment by CRKatri** [comment]
I hope to, but I probably won't get to it for a while, sorry.

**Comment by blacktop** [comment]
No worries! 👍

**Comment by blacktop** [comment]
I'm just going to merge this now as it's awesome and I'll try and improve the API to make tab tab easier to do 👍

**Pull request merged**
